//! Test-only helpers: synthetic Chief-shaped SQLite fixtures built with the
//! `sqlite3` CLI (tests silently skip when it is not installed). Nothing here
//! contains or copies Chief Architect content.

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::atomic::{AtomicUsize, Ordering};

pub const ROOT_UUID: &str = "00000000-0000-0000-0000-000000000001";
pub const DOORS_UUID: &str = "00000000-0000-0000-0000-000000000002";
pub const ENTRY_UUID: &str = "00000000-0000-0000-0000-000000000003";
pub const BIG_ROWS: usize = 3000;

/// A scratch directory removed on drop.
pub struct Scratch {
    dir: PathBuf,
}

impl std::ops::Deref for Scratch {
    type Target = Path;
    fn deref(&self) -> &Path {
        &self.dir
    }
}

impl Drop for Scratch {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.dir);
    }
}

/// Creates a fresh, unique directory for one test.
pub fn scratch_dir(name: &str) -> Scratch {
    static N: AtomicUsize = AtomicUsize::new(0);
    let dir = std::env::temp_dir().join(format!(
        "plan-calib-test-{}-{}-{name}",
        std::process::id(),
        N.fetch_add(1, Ordering::Relaxed)
    ));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("create scratch dir");
    Scratch { dir }
}

/// A database file generated by the `sqlite3` CLI.
pub struct Fixture {
    pub path: PathBuf,
    pub dir: Scratch,
}

impl Fixture {
    /// Runs `sql` through the `sqlite3` CLI into `<name>.calib`; `None` (and a
    /// note on stderr) when the CLI is unavailable.
    pub fn build(name: &str, sql: &str) -> Option<Fixture> {
        if Command::new("sqlite3").arg("-version").output().is_err() {
            eprintln!("sqlite3 CLI not found; skipping");
            return None;
        }
        let dir = scratch_dir(name);
        let path = dir.join(format!("{name}.calib"));
        let mut child = Command::new("sqlite3")
            .arg(&path)
            .stdin(Stdio::piped())
            .stdout(Stdio::null())
            .stderr(Stdio::piped())
            .spawn()
            .expect("spawn sqlite3");
        child
            .stdin
            .take()
            .unwrap()
            .write_all(sql.as_bytes())
            .expect("write sql");
        let out = child.wait_with_output().expect("wait sqlite3");
        assert!(
            out.status.success(),
            "sqlite3 failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
        Some(Fixture { path, dir })
    }

    /// The standard Chief-shaped fixture (3 objects, 3 tags, keywords,
    /// thumbnails incl. one spanning overflow pages, `AssociatedData`, and a
    /// 3000-row `Big` table with a multi-level b-tree).
    pub fn chief(name: &str) -> Option<Fixture> {
        Self::build(name, &chief_sql())
    }
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// A small fake PNG (signature + filler).
pub fn small_png() -> Vec<u8> {
    let mut v = b"\x89PNG\r\n\x1a\n".to_vec();
    v.extend(0..20u8);
    v
}

/// A fake PNG far larger than one 1 KiB page, forcing overflow pages.
pub fn overflow_thumbnail() -> Vec<u8> {
    let mut v = b"\x89PNG\r\n\x1a\n".to_vec();
    v.extend((0..9000usize).map(|i| (i * 7 % 251) as u8));
    v
}

pub fn big_text(id: i64) -> String {
    format!("row-{id}-{}", "x".repeat(id as usize % 40))
}

pub fn big_blob_len(id: i64) -> usize {
    (id as usize * 37) % 1300
}

pub fn big_blob(id: i64) -> Vec<u8> {
    (0..big_blob_len(id))
        .map(|i| ((i * 31 + id as usize) % 256) as u8)
        .collect()
}

fn assoc_blob_1() -> Vec<u8> {
    let json = br#"{"Version": 4, "Width": 36.5, "Macros": []}"#;
    let mut v = vec![0u8; 12];
    v.extend((json.len() as u32).to_le_bytes());
    v.extend_from_slice(json);
    v.extend((0..5000usize).map(|i| (i % 13) as u8));
    v
}

fn chief_sql() -> String {
    let mut s = String::new();
    s.push_str("PRAGMA page_size=1024;\n");
    s.push_str(
        "CREATE TABLE LibraryObjects (LibraryObjectId INTEGER PRIMARY KEY, Type INTEGER, Lock INTEGER, CopyrightId INTEGER, Metric INTEGER, ElementVersion INTEGER, LibSymDataId INTEGER DEFAULT NULL, PlantDataId INTEGER DEFAULT NULL, ProductFilterId INTEGER DEFAULT NULL, CreationTime TEXT DEFAULT NULL, ModificationTime TEXT DEFAULT NULL, UniqueId TEXT NOT NULL UNIQUE, Legacy_ShortcutDatabaseId INTEGER DEFAULT NULL, Legacy_ImportName TEXT DEFAULT NULL, Legacy_Name TEXT DEFAULT NULL, Notes TEXT DEFAULT NULL, ExtractionVersion INTEGER DEFAULT NULL, ProcessedFolders INTEGER NOT NULL DEFAULT 0, LinkTable BLOB DEFAULT NULL, Thumbnail BLOB DEFAULT NULL, PersistentId TEXT, CHECK(LENGTH(UniqueId) = 36));\n\
         CREATE TABLE Tags (TagUniqueId TEXT NOT NULL PRIMARY KEY, Name TEXT NOT NULL, GroupType INTEGER NOT NULL, ValueType INTEGER NOT NULL, Parent TEXT DEFAULT NULL, Color INTEGER NOT NULL DEFAULT 0, Pinned INTEGER NOT NULL DEFAULT 0 CHECK (Pinned IN (0, 1)), FOREIGN KEY(Parent) REFERENCES Tags(TagUniqueId) ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE, CHECK(LENGTH(TagUniqueId) = 36));\n\
         CREATE TABLE Tags4LibraryObjects (Tags4LibraryObjectsId INTEGER PRIMARY KEY, LibraryObjectUniqueId TEXT NOT NULL, TagUniqueId TEXT NOT NULL, Value BLOB DEFAULT NULL, Alias TEXT DEFAULT NULL, FOREIGN KEY(TagUniqueId) REFERENCES Tags(TagUniqueId), FOREIGN KEY(LibraryObjectUniqueId) REFERENCES LibraryObjects(UniqueId));\n\
         CREATE TABLE Keywords (KeywordId INTEGER PRIMARY KEY, Keyword TEXT UNIQUE COLLATE NOCASE);\n\
         CREATE TABLE Keywords4LibraryObjects (LibraryObjectId INTEGER, KeywordId INTEGER, AutoGenerated INTEGER NOT NULL DEFAULT 0);\n\
         CREATE TABLE AssociatedData (AssociatedDataId INTEGER PRIMARY KEY, AssociatedDataBlob BLOB DEFAULT NULL);\n\
         CREATE TABLE GlobalData (GlobalId INTEGER PRIMARY KEY, CategoryId INTEGER DEFAULT 0, Lock INTEGER DEFAULT 0, convertedAlbs INTEGER DEFAULT 0, DatabaseUniqueId TEXT, Retired INTEGER NOT NULL DEFAULT 0, ExportVersion TEXT DEFAULT NULL, NeedsIDScrambling INTEGER DEFAULT 0);\n\
         CREATE TABLE Big (Id INTEGER PRIMARY KEY, T TEXT, R REAL, B BLOB);\n",
    );
    s.push_str("BEGIN;\n");
    let obj = |id: u32, ty: u32, metric: u32, legacy: &str, thumb: &str| {
        format!(
            "INSERT INTO LibraryObjects (LibraryObjectId, Type, Lock, Metric, UniqueId, Legacy_Name, Thumbnail) VALUES ({id}, {ty}, 0, {metric}, 'aaaaaaaa-0000-0000-0000-00000000000{id}', {legacy}, {thumb});\n"
        )
    };
    s.push_str(&obj(1, 7, 0, "NULL", &format!("X'{}'", hex(&small_png()))));
    s.push_str(&obj(2, 12, 1, "'Legacy Thing'", "NULL"));
    s.push_str(&obj(
        3,
        0,
        0,
        "NULL",
        &format!("X'{}'", hex(&overflow_thumbnail())),
    ));
    s.push_str(&format!(
        "INSERT INTO Tags VALUES ('{ROOT_UUID}', 'Fixtures', 2, 43, NULL, 4294967295, 0);\n\
         INSERT INTO Tags VALUES ('{DOORS_UUID}', 'Doors', 2, 43, '{ROOT_UUID}', 4294967295, 0);\n\
         INSERT INTO Tags VALUES ('{ENTRY_UUID}', 'Entry Doors', 2, 43, '{DOORS_UUID}', 4294967295, 0);\n\
         INSERT INTO Tags4LibraryObjects (LibraryObjectUniqueId, TagUniqueId, Alias) VALUES ('aaaaaaaa-0000-0000-0000-000000000001', '{ENTRY_UUID}', 'Door One');\n\
         INSERT INTO Tags4LibraryObjects (LibraryObjectUniqueId, TagUniqueId, Alias) VALUES ('aaaaaaaa-0000-0000-0000-000000000002', '{DOORS_UUID}', NULL);\n\
         INSERT INTO Tags4LibraryObjects (LibraryObjectUniqueId, TagUniqueId, Alias) VALUES ('aaaaaaaa-0000-0000-0000-000000000003', '{ROOT_UUID}', '');\n\
         INSERT INTO Keywords VALUES (1, 'Oak');\n\
         INSERT INTO Keywords VALUES (2, 'Front');\n\
         INSERT INTO Keywords4LibraryObjects VALUES (1, 1, 0);\n\
         INSERT INTO Keywords4LibraryObjects VALUES (1, 2, 0);\n\
         INSERT INTO Keywords4LibraryObjects VALUES (1, 1, 1);\n\
         INSERT INTO Keywords4LibraryObjects VALUES (2, 2, 0);\n\
         INSERT INTO GlobalData (GlobalId, DatabaseUniqueId, ExportVersion) VALUES (1, '{ROOT_UUID}', '28.0');\n"
    ));
    s.push_str(&format!(
        "INSERT INTO AssociatedData VALUES (1, X'{}');\n\
         INSERT INTO AssociatedData VALUES (2, NULL);\n\
         INSERT INTO AssociatedData VALUES (3, X'{}');\n",
        hex(&assoc_blob_1()),
        hex(&[0xaa; 40])
    ));
    for id in 1..=BIG_ROWS as i64 {
        s.push_str(&format!(
            "INSERT INTO Big VALUES ({id}, '{}', {}, X'{}');\n",
            big_text(id),
            id as f64 / 4.0,
            hex(&big_blob(id))
        ));
    }
    s.push_str("COMMIT;\n");
    s
}
